---
#
# Site specific values to override defaults for variables.
#
# Conventions for global environment variables:
# Use UPPERCASE underscore separated names like for shell env vars.
#
# Conventions for playbook variables:
# Use lowercase underscore separated names.
#
stack_prefix: 'tl'
#
# Versions of components of our HPC environment, which is managed using Lua+Lmod+EasyBuild.
# NOTE: when introducing a new version number here,
#       please make sure to add corresponding values in group_vars/all.yml
#
lua_version: '5.4.6'
luaposix_version: '36.2.1'
lmod_version: '8.7.32'
easybuild_version: '4.9.4'
eb_user: umcg-envsync
extra_easyconfigs_version: 25.01.1
extra_easyconfigs_repository: 'take-it-easyconfigs'
#
# Group folder structures to construct on shared storage systems.
#
group_subfolder_structure:
  ######################################################################################################################
  # umcg-atd group
  ######################################################################################################################
  - group: umcg-atd
    lfs: tmp08
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-atd-ateambot
    subfolders: "{{ analysis_folders['ConcordanceCheck']['tmp']
            | union(analysis_folders['NGS_Demultiplexing']['tmp'])
            | union(analysis_folders['NGS_DNA']['tmp'])
            | union(analysis_folders['trendanalysis']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-atd
    lfs: prm08
    mode: "{{ MODE_2750_HARD }}"
    owner: umcg-atd-dm
    subfolders: "{{ analysis_folders['ConcordanceCheck']['prm']
            | union(analysis_folders['NGS_Demultiplexing']['prm'])
            | union(analysis_folders['NGS_DNA']['prm'])
            | union(analysis_folders['trendanalysis']['prm']) }}"
    machines: "{{ groups['user_interface'] }}"
#
# Sources, software and reference data to install/fetch.
#
public_sources: []
private_sources: []
refdata: []
static_easyconfigs:
  - 'c/cluster-utils/cluster-utils-v25.01.2-GCCcore-11.3.0.eb'
  - 'd/depad-utils/depad-utils-v24.04.1.eb'
...
