---
- name: Create folder structure for extra EasyConfigs.
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: "{{ MODE_2775_HARD }}"
  with_items:
    - "{{ extra_easyconfigs_prefix }}"
    - "{{ easybuild_sources_dir }}/e/easyconfigs"
  become: "{% if eb_user is defined and eb_user | length > 0 %}true{% else %}false{% endif %}"
  become_user: "{{ eb_user | default(omit) }}"

- name: Get EasyConfigs.
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    checksum: "{{ item.checksum }}"
    mode: "{{ MODE_0664_HARD }}"
    timeout: 30
  with_items:
    - url: "https://github.com/molgenis/{{ extra_easyconfigs_repository }}/archive/refs/tags/{{ extra_easyconfigs_version }}.tar.gz"
      dest: "{{ easybuild_sources_dir }}/e/easyconfigs/"
      checksum: "{{ extra_easyconfigs_releases[extra_easyconfigs_version]['checksum'] }}"
  become: "{% if eb_user is defined and eb_user | length > 0 %}true{% else %}false{% endif %}"
  become_user: "{{ eb_user | default(omit) }}"

- name: Extract EasyConfigs.
  ansible.builtin.unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: true
    mode: "{{ MODE__775_SOFT }}"
  with_items:
    - src: "{{ easybuild_sources_dir }}/e/easyconfigs/{{ extra_easyconfigs_repository }}-{{ extra_easyconfigs_version }}.tar.gz"
      dest: "{{ easybuild_software_dir }}/easyconfigs"
  become: "{% if eb_user is defined and eb_user | length > 0 %}true{% else %}false{% endif %}"
  become_user: "{{ eb_user | default(omit) }}"
...
