---
- name: Create subfolder structures for groups.
  ansible.builtin.file:
    dest: "{{ path }}"
    state: directory
    group: "{{ item.0.group }}"
    mode: "{{ item.0.mode }}"
  become: "{% if item.0.owner is defined and item.0.owner | length %}true{% else %}false{% endif %}"
  become_user: "{% if item.0.owner is defined and item.0.owner | length %}{{ item.0.owner }}{% endif %}"
  vars:
    path: "{{ hpc_groups_prefix }}/{{ item.0.group }}/{{ item.0.lfs }}/{{ item.1 }}"
    loop_label_attributes:
      - owner
      - group
      - mode
  loop: "{{ group_subfolder_structure | subelements('subfolders') }}"
  loop_control:
    label: "{{ item.0 | subsetattrs(loop_label_attributes) | combine({ 'path': path}) }}"
  when: inventory_hostname in item.0.machines
...
